Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/YodaCondition:
  Enabled: false

  # Offense count: 5
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 50

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false